### PR TITLE
Initial foosball rules scraper (USTSA)

### PR DESCRIPTION
**Pull request by Ian-Stewart-Binks**
Not yet completed. @emmettu any suggestions? The [page](http://www.foosball.com/learn/rules/ustsa/) might be tough to parse.

### CODE REVIEW

**Comment by Ian-Stewart-Binks** [comment]
Eventually, we want the rules to be parsed into a json object like this:

```
[{
    "section": "Serves",
    "rules": [{
        "description": "xyz"
    }]

}, {
    "section": "Blah",
    "rules": [{
        "description": "xyz"
    }]

}]
```

**Comment by Ian-Stewart-Binks** [comment]
Actually, probably easier to just format into JSON by hand.

**Comment by emmettu** [comment]
@Ian-Stewart-Binks I could look into scraping it. It would be useful to be able to grab the most up to date rules.

**Comment by Ian-Stewart-Binks** [comment]
@emmettu Sure. Do you want to take over the script?

**Comment by Ian-Stewart-Binks** [comment]
Note there is also [this](http://www.foosball.com/learn/rules/onepage/) page

**Comment by emmettu** [comment]
I can give it a look yes.

**Pull request closed without merging**
