### PR TITLE
Clean up scrape.py

### PR DESCRIPTION
**Pull request by Ian-Stewart-Binks**
Signed-off-by: Ian Stewart-Binks istewartbinks@gmail.com

### CODE REVIEW

**Comment by emmettu** [comment]
:+1: amazing work.

**Comment by Ian-Stewart-Binks** [comment]
I know.

**Comment by emmettu** [comment]
Why is the travis job being run twice?

**Comment by Ian-Stewart-Binks** [comment]
Because are settings are a little funky. It does it for the push and the pr.

**Comment by emmettu** [comment]
Oh wait I keep forgetting the repo is under your name. That explains where the push job is coming from.

**Pull request merged**
