### PR TITLE
Jsonize rules

### PR DESCRIPTION
**Pull request by Ian-Stewart-Binks**

### CODE REVIEW

**Comment by Ian-Stewart-Binks** [comment]
@Anirudh94 Please review.

**Comment by Anirudh94** [comment]
Looks good to me, can you please squash your commits though?

**Comment by Ian-Stewart-Binks** [comment]
Will do.

**Comment by Ian-Stewart-Binks** [comment]
Done.

**Comment by Anirudh94** [comment]
Cool thanks!

**Pull request merged**
